### ISSUE TITLE
Create post-lui tower tasks

### ISSUE THREAD

**Issue by sgriffith3** [alta3/lui#3]
This is where we will list the tasks that need done after lui in order to have fully operational tower environments. 

This information has primarily been gathered here: https://github.com/alta3/alta3-ansible/issues/149, but still needs to be turned into Ansible tasks.

**Comment by seaneon** [comment]
OBE. work is being done here: https://github.com/alta3/alta3-ansible/tree/undercloud_v1.1/undercloud_playbooks/lui
